<?php
if(!defined('ABSPATH'))exit;
$seller=wp_create_user('private-seller','test-only-password','seller@example.invalid');$buyer=wp_create_user('private-buyer','test-only-password','buyer@example.invalid');
check(call_api('GET','/particulier/woningen')->get_status()===401,'private management requires authentication');
$res=call_api('POST','/particulier/woningen',['publication_status'=>'publish'],$seller);check($res->get_status()===400,'private seller cannot self-publish');
check(call_api('POST','/particulier/woningen',['transactie'=>'Huur'],$seller)->get_status()===400,'private rental not enabled accidentally');
$fields=['title'=>'Zelf te koop','description'=>'CI woning omschrijving','adres'=>'Duinweg 1','postcode'=>'3235AA','plaats'=>'Rockanje','prijs'=>'425.000','woningtype'=>'Woning','woonoppervlak'=>'120','energielabel'=>'A','transactie'=>'Koop','status'=>'Beschikbaar'];
$res=call_api('POST','/particulier/woningen',$fields,$seller);check($res->get_status()===200,'ordinary account creates private sale draft');$pid=$res->get_data()['id'];
check(!in_array(RVAZ_Wonen::ROLE,(new WP_User($seller))->roles,true),'private seller does not gain realtor role');
check(call_api('POST','/particulier/woningen',$fields,$seller)->get_status()===409,'one private home per account enforced');
check(call_api('POST',"/particulier/woningen/$pid",['title'=>'Foreign change'],$buyer)->get_status()===403,'another seller cannot edit private draft');
check(call_api('POST',"/particulier/woningen/$pid/fotos",[],$buyer)->get_status()===403,'another seller cannot upload photo');
check(call_api('GET','/particulier/woningen',[],$buyer)->get_data()===[],'private inventory isolated by account');
$terms=['authority_confirmed'=>true,'photos_confirmed'=>true];
check(call_api('POST',"/particulier/woningen/$pid/indienen",$terms,$seller)->get_status()===400,'incomplete missing-photo submission rejected');
$aid=wp_insert_attachment(['post_title'=>'Synthetic photo','post_mime_type'=>'image/jpeg','post_author'=>$seller,'post_status'=>'inherit']);update_post_meta($aid,'_wp_attached_file','2026/10/synthetic.jpg');set_post_thumbnail($pid,$aid);update_post_meta($pid,'_rvaz_wonen_gallery',[$aid]);
check(call_api('POST',"/particulier/woningen/$pid/indienen",['authority_confirmed'=>false,'photos_confirmed'=>true],$seller)->get_status()===400,'authority confirmation required');
check(call_api('POST',"/particulier/woningen/$pid/indienen",$terms,$seller)->get_status()===200&&get_post_status($pid)==='pending','complete confirmed home submitted for review');
check(call_api('POST',"/beheer/particulier/$pid",['decision'=>'approve','authority_checked'=>true],$seller)->get_status()===401||call_api('POST',"/beheer/particulier/$pid",['decision'=>'approve','authority_checked'=>true],$seller)->get_status()===403,'owner cannot act as moderator');
$order=['confirm'=>true,'expected_price'=>'25.00','expected_period'=>'1_month'];
check(call_api('POST',"/particulier/woningen/$pid/bestellen",$order,$seller)->get_status()===400,'billing waits for actual RVAZ review');
check(call_api('POST',"/beheer/particulier/$pid",['decision'=>'approve','authority_checked'=>true],1)->get_data()['status']==='awaiting_payment','approval without payment never publishes');
check(get_post_meta($pid,'_rvaz_wonen_private_expires',true)==='','review waiting time consumes no paid period');
check(call_api('POST',"/particulier/woningen/$pid/bestellen",['confirm'=>true,'expected_price'=>'1','expected_period'=>'1_month'],$seller)->get_status()===409,'incorrect private tariff cannot create invoice');
$private_invoice=call_api('POST',"/particulier/woningen/$pid/bestellen",$order,$seller)->get_data()['invoice_id'];
check(call_api('POST',"/particulier/woningen/$pid/bestellen",$order,$seller)->get_data()['invoice_id']===$private_invoice,'private order retry creates no duplicate invoice');
global $wpdb;$bill=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}rvaz_wonen_invoices WHERE id=%d",$private_invoice));check((float)$bill->total===25.0&&$bill->status==='open','one-home one-month invoice totals exactly 25 euros');
check(call_api('GET',"/particulier/facturen/$private_invoice/pdf",[],$buyer)->get_status()===403,'private invoice PDF protected from other account');
check(call_api('GET',"/particulier/facturen/$private_invoice/pdf",[],$seller)->get_status()===200,'seller can download own private invoice');
wp_set_current_user($seller);wp_update_post(['ID'=>$pid,'post_status'=>'publish']);check(get_post_status($pid)!=='publish','direct publish bypass blocked before payment and approval');
$wpdb->update($wpdb->prefix.'rvaz_wonen_invoices',['status'=>'paid'],['id'=>$private_invoice]);
check(call_api('POST',"/beheer/particulier/$pid",['decision'=>'approve','authority_checked'=>true],1)->get_status()===200&&get_post_status($pid)==='publish','paid reviewed property is published by administrator');
$expiry=(int)get_post_meta($pid,'_rvaz_wonen_private_expires',true);check($expiry>time()+27*DAY_IN_SECONDS,'calendar-month period starts upon publication');
$public=call_api('GET','/woningen')->get_data();$property=current(array_filter($public,function($d)use($pid){return $d['id']===$pid;}));check($property['aanbieder_type']==='Particulier'&&$property['makelaar_naam']==='Particulier aanbod'&&strpos(wp_json_encode($property),'seller@example.invalid')===false,'public private offer is labeled without seller email');
check(in_array($pid,array_column(call_api('GET','/uitgelicht')->get_data(),'id'),true),'paid approved private advert featured on app home');
$contact=['name'=>'Buyer','email'=>'buyer@example.invalid','message'=>'Interesse in deze woning'];check(call_api('POST',"/woningen/$pid/contact",$contact)->get_status()===200,'visitor can contact private seller natively');
call_api('POST',"/woningen/$pid/contact",$contact);check(count(call_api('GET','/particulier/aanvragen',[],$seller)->get_data())===1,'contact retries create a single private lead');
check(call_api('GET','/particulier/aanvragen',[],$buyer)->get_data()===[],'seller inquiry inbox cannot leak to another account');
check(call_api('POST',"/particulier/woningen/$pid",['title'=>'Aangepast'],$seller)->get_status()===200&&get_post_status($pid)==='draft','seller changes remove live offer until re-review');
check((int)get_post_meta($pid,'_rvaz_wonen_private_expires',true)===$expiry,'editing cannot silently extend purchased period');
call_api('POST',"/particulier/woningen/$pid/indienen",$terms,$seller);call_api('POST',"/beheer/particulier/$pid",['decision'=>'approve','authority_checked'=>true],1);check((int)get_post_meta($pid,'_rvaz_wonen_private_expires',true)===$expiry,'re-approval of paid advert preserves original end date');
update_post_meta($pid,'_rvaz_wonen_private_expires',time()-1);call_api('GET','/woningen');check(get_post_status($pid)==='draft','expired private offer removed from public stock without relying on cron');
check(!in_array($pid,array_column(call_api('GET','/uitgelicht')->get_data(),'id'),true),'expired private advert excluded from home');
check(call_api('POST',"/woningen/$pid/contact",$contact)->get_status()===404,'expired property cannot receive new inquiries');
call_api('POST',"/particulier/woningen/$pid/indienen",$terms,$seller);
check(call_api('POST',"/beheer/particulier/$pid",['decision'=>'approve','authority_checked'=>true],1)->get_data()['status']==='awaiting_payment','new reviewed placement after expiry needs a new payment');
$renewal=call_api('POST',"/particulier/woningen/$pid/bestellen",$order,$seller)->get_data()['invoice_id'];
check($renewal!==$private_invoice&&!RVAZ_Wonen_Private::paid($pid),'old paid invoice cannot fund a second month');
$wpdb->update($wpdb->prefix.'rvaz_wonen_invoices',['status'=>'paid'],['id'=>$renewal]);
check(call_api('POST',"/beheer/particulier/$pid",['decision'=>'approve','authority_checked'=>true],1)->get_status()===200&&(int)get_post_meta($pid,'_rvaz_wonen_private_expires',true)>time()+27*DAY_IN_SECONDS,'explicitly paid new placement starts a new calendar month');
$jan=(new DateTimeImmutable('2027-01-31 12:15:00',wp_timezone()))->getTimestamp();check(wp_date('Y-m-d H:i',RVAZ_Wonen_Private::month_end($jan))==='2027-02-28 12:15','one calendar month clamps month end instead of overflowing into March');
wp_delete_post($pid,true);wp_delete_attachment($aid,true);
$intro_user=wp_create_user('intro-agent','test-only-password','intro@example.invalid');$wpdb->insert($wpdb->prefix.'rvaz_wonen_applications',['user_id'=>$intro_user,'office'=>'Intro kantoor','plan'=>'plus','contact_name'=>'New agent','phone'=>'123','status'=>'pending','created'=>current_time('mysql')]);$app=$wpdb->insert_id;
check(RVAZ_Wonen_Intro::plans($intro_user)['plus']['first_month_price']==='49.50','50 percent first-month quote for new broker');
$approved=RVAZ_Wonen_Intro::approve($app,'approve');check(!is_wp_error($approved)&&$approved['discount_applied']===true,'new broker approval applies introduction offer');
$intro_bill=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}rvaz_wonen_invoices WHERE id=%d",$approved['invoice_id']));check((float)$intro_bill->total===49.5,'Plus first-month invoice is half of regular 99');
check(is_wp_error(RVAZ_Wonen_Intro::approve($app,'approve')),'approval replay cannot duplicate initial invoice');
$next=RVAZ_Wonen::create_invoice($intro_user,'plus');check((float)$wpdb->get_var($wpdb->prepare("SELECT total FROM {$wpdb->prefix}rvaz_wonen_invoices WHERE id=%d",$next))===99.0,'subsequent broker invoice returns to full monthly price');
check(!RVAZ_Wonen_Intro::eligible($agent),'historical broker account is not discounted retroactively');
check((float)$wpdb->get_var("SELECT total FROM {$wpdb->prefix}rvaz_wonen_invoices WHERE invoice_no='PROTECTED-OLD'")===121.0,'introduction offer leaves historical paid invoice unchanged');
