import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:qr_flutter/qr_flutter.dart';

const site='https://regiovoorneaanzee.nl';
Future<Map<String,String>> ah() async {final t=await const FlutterSecureStorage().read(key:'rvaz_token');return {'Accept':'application/json',if(t!=null&&t.isNotEmpty)'Authorization':'Bearer '+t};}

class MyVouchersPage extends StatefulWidget{const MyVouchersPage({super.key});@override State<MyVouchersPage> createState()=>_MyVouchersPageState();}
class _MyVouchersPageState extends State<MyVouchersPage>{late Future<List<dynamic>> f;@override void initState(){super.initState();f=load();}Future<List<dynamic>>load()async{final r=await http.get(Uri.parse(site+'/wp-json/rvaz-vouchers/v1/mine'),headers:await ah());if(r.statusCode==401)throw Exception('Log eerst in bij Mijn RVAZ.');return r.statusCode==200?List<dynamic>.from(jsonDecode(r.body)):[];}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Mijn vouchers')),body:FutureBuilder<List<dynamic>>(future:f,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text(s.error.toString()));final x=s.data??[];return ListView(padding:const EdgeInsets.all(16),children:x.map((e){final used=e['status']=='redeemed',v=e['voucher']??{},qr=(e['qr_value']??'').toString();return Card(margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((v['business']??'').toString(),style:const TextStyle(fontWeight:FontWeight.w900)),Text((v['offer']??v['title']??'').toString()),const SizedBox(height:10),if(!used&&qr.isNotEmpty)Center(child:QrImageView(data:qr,size:210)),if(!used)Center(child:Text((e['code']??'').toString(),style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18))),if(used)Text('✓ Ingewisseld'+((e['redeemed_at_display']??'').toString().isNotEmpty?' op '+e['redeemed_at_display'].toString():''),style:const TextStyle(fontWeight:FontWeight.w900,color:Color(0xFF176B35)))])));}).toList());}));}

class VoucherRedeemPage extends StatefulWidget{final String token;const VoucherRedeemPage({super.key,required this.token});@override State<VoucherRedeemPage> createState()=>_VoucherRedeemPageState();}
class _VoucherRedeemPageState extends State<VoucherRedeemPage>{Map<String,dynamic>? d;String? err;bool busy=true;@override void initState(){super.initState();load();}Future<void>load()async{final r=await http.get(Uri.parse(site+'/wp-json/rvaz-vouchers/v1/check/'+Uri.encodeComponent(widget.token)),headers:await ah());if(!mounted)return;if(r.statusCode==200)setState((){d=Map<String,dynamic>.from(jsonDecode(r.body));busy=false;err=null;});else setState((){busy=false;err='Log in met het gekoppelde PRO-bedrijfsaccount of controleer deze voucher.';});}Future<void>redeem()async{setState(()=>busy=true);final r=await http.post(Uri.parse(site+'/wp-json/rvaz-vouchers/v1/redeem/'+Uri.encodeComponent(widget.token)),headers:await ah());if(r.statusCode>=200&&r.statusCode<300)await load();else if(mounted)setState((){busy=false;err='Inwisselen mislukt.';});}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Voucher inwisselen')),body:busy?const Center(child:CircularProgressIndicator()):err!=null?Center(child:Padding(padding:const EdgeInsets.all(24),child:Text(err!,textAlign:TextAlign.center))):ListView(padding:const EdgeInsets.all(18),children:[Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(d?['status']=='redeemed'?'✓ Ingewisseld':'✓ Voucher geldig',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:14),Text('Bedrijf: '+(d?['voucher']?['business']??'').toString()),Text('Aanbieding: '+(d?['voucher']?['offer']??'').toString(),style:const TextStyle(fontWeight:FontWeight.w900)),Text('Voucher: '+(d?['code']??'').toString()),if(d?['status']=='redeemed')Text('Ingewisseld: '+(d?['redeemed_at_display']??'').toString()),const SizedBox(height:16),if(d?['status']!='redeemed')SizedBox(width:double.infinity,child:FilledButton(onPressed:redeem,child:const Text('VOUCHER INWISSELEN')))else const Text('Deze voucher kan niet opnieuw worden ingewisseld.')])))]));}

class BusinessVoucherScannerPage extends StatefulWidget{const BusinessVoucherScannerPage({super.key});@override State<BusinessVoucherScannerPage> createState()=>_BusinessVoucherScannerPageState();}
class _BusinessVoucherScannerPageState extends State<BusinessVoucherScannerPage>{bool done=false;void detect(BarcodeCapture c){if(done||c.barcodes.isEmpty)return;final raw=c.barcodes.first.rawValue??'';if(raw.isEmpty)return;final u=Uri.tryParse(raw);final t=(u?.queryParameters['token']??u?.queryParameters['rvaz_voucher_scan']??raw).trim();if(t.isEmpty)return;setState(()=>done=true);Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>VoucherRedeemPage(token:t)));}@override Widget build(BuildContext c)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(title:const Text('Voucher scannen')),body:Stack(children:[MobileScanner(onDetect:detect),Center(child:Container(width:260,height:260,decoration:BoxDecoration(border:Border.all(color:Colors.white,width:3),borderRadius:BorderRadius.circular(18)))),const Positioned(left:20,right:20,bottom:40,child:Text('Richt de camera op de RVAZ QR-code',textAlign:TextAlign.center,style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800)))]));}

class BusinessManagePage extends StatefulWidget{const BusinessManagePage({super.key});@override State<BusinessManagePage> createState()=>_BusinessManagePageState();}
class _BusinessManagePageState extends State<BusinessManagePage>{Map<String,dynamic>? b;bool busy=true;final title=TextEditingController(),desc=TextEditingController(),address=TextEditingController(),phone=TextEditingController(),website=TextEditingController();Map<String,dynamic> hours={};@override void initState(){super.initState();load();}Future<void>load()async{final r=await http.get(Uri.parse(site+'/wp-json/rvaz-business/v1/mine'),headers:await ah());if(!mounted)return;if(r.statusCode!=200){setState(()=>busy=false);return;}final x=Map<String,dynamic>.from(jsonDecode(r.body));setState((){b=x;title.text=(x['title']??'').toString();desc.text=(x['description']??'').toString();address.text=(x['address']??'').toString();phone.text=(x['phone']??'').toString();website.text=(x['website']??'').toString();hours=x['hours'] is Map?Map<String,dynamic>.from(x['hours']):{};busy=false;});}Future<void>save()async{final r=await http.post(Uri.parse(site+'/wp-json/rvaz-business/v1/mine'),headers:{...await ah(),'Content-Type':'application/json'},body:jsonEncode({'title':title.text,'description':desc.text,'address':address.text,'phone':phone.text,'website':website.text,'hours':hours}));if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(r.statusCode>=200&&r.statusCode<300?'Wijzigingen verstuurd en wachten op controle.':'Opslaan mislukt.')));}}@override Widget build(BuildContext c){if(busy)return const Scaffold(body:Center(child:CircularProgressIndicator()));if(b==null)return const Scaffold(body:Center(child:Text('Aan dit account is geen bedrijf gekoppeld.')));return DefaultTabController(length:2,child:Scaffold(appBar:AppBar(title:const Text('Mijn bedrijf'),actions:[IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const BusinessVoucherScannerPage())),icon:const Icon(Icons.qr_code_scanner))],bottom:const TabBar(tabs:[Tab(text:'Gegevens'),Tab(text:'Openingstijden')])),body:TabBarView(children:[ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Bedrijfsnaam')),const SizedBox(height:10),TextField(controller:desc,minLines:5,maxLines:10,decoration:const InputDecoration(labelText:'Omschrijving')),const SizedBox(height:10),TextField(controller:address,decoration:const InputDecoration(labelText:'Adres')),const SizedBox(height:10),TextField(controller:phone,decoration:const InputDecoration(labelText:'Telefoon')),if(b?['pro']==true)...[const SizedBox(height:10),TextField(controller:website,decoration:const InputDecoration(labelText:'Website'))],const SizedBox(height:16),FilledButton(onPressed:save,child:const Text('Wijzigingen versturen')),const SizedBox(height:10),OutlinedButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const BusinessVoucherScannerPage())),icon:const Icon(Icons.qr_code_scanner),label:const Text('Voucher scannen'))]),OpeningHoursEditor(hours:hours,onSave:save)])));}}

class OpeningHoursEditor extends StatefulWidget{final Map<String,dynamic> hours;final Future<void> Function() onSave;const OpeningHoursEditor({super.key,required this.hours,required this.onSave});@override State<OpeningHoursEditor> createState()=>_OpeningHoursEditorState();}
class _OpeningHoursEditorState extends State<OpeningHoursEditor>{@override Widget build(BuildContext c){const days={'monday':'Maandag','tuesday':'Dinsdag','wednesday':'Woensdag','thursday':'Donderdag','friday':'Vrijdag','saturday':'Zaterdag','sunday':'Zondag'};return ListView(padding:const EdgeInsets.all(16),children:[...days.entries.map((e){final d=widget.hours[e.key] is Map?Map<String,dynamic>.from(widget.hours[e.key]):<String,dynamic>{};final closed=d['closed']==true||d['closed']==1||d['closed']=='1';return Card(margin:const EdgeInsets.only(bottom:10),child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Row(children:[Expanded(child:Text(e.value,style:const TextStyle(fontWeight:FontWeight.w900))),Switch(value:closed,onChanged:(v)=>setState(()=>widget.hours[e.key]={...d,'closed':v}))]),if(!closed)Row(children:[Expanded(child:TextFormField(initialValue:(d['open']??'').toString(),decoration:const InputDecoration(labelText:'Van'),onChanged:(v)=>widget.hours[e.key]={...d,'open':v})),const SizedBox(width:10),Expanded(child:TextFormField(initialValue:(d['close']??'').toString(),decoration:const InputDecoration(labelText:'Tot'),onChanged:(v)=>widget.hours[e.key]={...d,'close':v}))])])));}),FilledButton(onPressed:widget.onSave,child:const Text('Openingstijden versturen'))]);}}
