<?php
if(!defined('ABSPATH'))exit;
final class RVAZ_Wonen_Invoice_Mail {
 static function row($id){global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}rvaz_wonen_invoices WHERE id=%d",absint($id)));}
 static function allowed($r){if(!current_user_can('manage_options'))return RVAZ_Wonen_Native_API::error('admin','Alleen RVAZ-beheer mag facturen versturen.',403);if(!$r)return RVAZ_Wonen_Native_API::error('invoice','Factuur niet gevonden.',404);if($r->status!=='open'||RVAZ_Wonen_Invoice_Tools::removed($r->id))return RVAZ_Wonen_Native_API::error('status','Alleen een actieve open factuur kan een betaalverzoek krijgen.',409);return true;}
 static function save_link($id,$link){$r=self::row($id);$ok=self::allowed($r);if(is_wp_error($ok))return $ok;$link=esc_url_raw($link,['https']);if(!$link||!wp_http_validate_url($link)||wp_parse_url($link,PHP_URL_SCHEME)!=='https')return RVAZ_Wonen_Native_API::error('url','Gebruik een volledige HTTPS-betaallink.');global $wpdb;if($wpdb->update($wpdb->prefix.'rvaz_wonen_invoices',['tikkie_url'=>$link],['id'=>$r->id,'status'=>'open'])===false)return RVAZ_Wonen_Native_API::error('database','Betaallink opslaan is niet gelukt.',500);return ['status'=>'saved'];}
 static function send($id){
  $r=self::row($id);$ok=self::allowed($r);if(is_wp_error($ok))return $ok;
  if(!$r->tikkie_url||wp_parse_url($r->tikkie_url,PHP_URL_SCHEME)!=='https'||!wp_http_validate_url($r->tikkie_url))return RVAZ_Wonen_Native_API::error('link','Sla eerst een geldige HTTPS Tikkie-link op.');
  $u=get_userdata($r->user_id);if(!$u||!is_email($u->user_email))return RVAZ_Wonen_Native_API::error('recipient','Het account heeft geen geldig e-mailadres.');
  $pdf=RVAZ_Wonen_Native_API::render_invoice_pdf($r,$u);$dir=trailingslashit(get_temp_dir()).'rvaz-invoice-'.wp_generate_uuid4();if(!wp_mkdir_p($dir))return RVAZ_Wonen_Native_API::error('pdf','PDF voorbereiden is niet gelukt.',500);chmod($dir,0700);$file=trailingslashit($dir).$pdf['filename'];if(file_put_contents($file,base64_decode($pdf['pdf_base64']))===false){wp_delete_file($file);rmdir($dir);return RVAZ_Wonen_Native_API::error('pdf','PDF voorbereiden is niet gelukt.',500);}
  try{$sent=wp_mail($u->user_email,'RVAZ factuur '.$r->invoice_no,'Beste '.$u->display_name.",\n\nBijgevoegd vind je factuur ".$r->invoice_no.' van €'.number_format((float)$r->total,2,',','.').".\n\nBetalen via Tikkie:\n".$r->tikkie_url."\n\nMet vriendelijke groet,\nRVAZ",[],[$file]);}finally{wp_delete_file($file);rmdir($dir);}
  if(!$sent)return RVAZ_Wonen_Native_API::error('mail','Verzenden is niet gelukt. De factuur en betaalstatus zijn behouden.',500);
  update_option('rvaz_wonen_invoice_sent_'.absint($id),['time'=>current_time('mysql'),'by'=>get_current_user_id()],false);return ['status'=>'sent'];
 }
 static function page(){
  if(!current_user_can('manage_options'))return;global $wpdb;$rows=$wpdb->get_results("SELECT i.*,u.user_email FROM {$wpdb->prefix}rvaz_wonen_invoices i LEFT JOIN {$wpdb->users} u ON i.user_id=u.ID WHERE i.status='open' ORDER BY i.id DESC");
  echo '<div class="wrap"><h1>Factuur + Tikkie versturen</h1><p>Voor makelaars en particulieren: maak zelf de Tikkie voor het factuurbedrag, plak de link en sla deze op. Verstuur daarna de PDF-factuur en Tikkie-link naar het e-mailadres van de klant.</p><table class="widefat striped"><tr><th>Factuur / klant</th><th>Bedrag</th><th>Tikkie-link</th><th>Versturen</th></tr>';
  foreach($rows as $r){if(RVAZ_Wonen_Invoice_Tools::removed($r->id))continue;echo '<tr><td>'.esc_html($r->invoice_no).'<br>'.esc_html($r->user_email).'</td><td>€'.esc_html(number_format((float)$r->total,2,',','.')).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="rvaz_wonen_invoice_mail"><input type="hidden" name="operation" value="save"><input type="hidden" name="id" value="'.(int)$r->id.'">'.wp_nonce_field('rvaz_wonen_invoice_mail_'.$r->id,'nonce',true,false).'<input type="url" name="tikkie_url" required style="width:100%" value="'.esc_attr($r->tikkie_url).'"><button class="button">Link opslaan</button></form></td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="rvaz_wonen_invoice_mail"><input type="hidden" name="operation" value="send"><input type="hidden" name="id" value="'.(int)$r->id.'">'.wp_nonce_field('rvaz_wonen_invoice_mail_'.$r->id,'nonce',true,false).'<label><input type="checkbox" name="confirm" value="1" required> Verstuur naar '.esc_html($r->user_email).'</label><button class="button button-primary" '.(!$r->tikkie_url?'disabled':'').'>Factuur + Tikkie mailen</button></form></td></tr>';}
  echo '</table></div>';
 }
}
add_action('admin_menu',function(){add_submenu_page('rvaz-wonen','Factuur + Tikkie','Factuur + Tikkie','manage_options','rvaz-wonen-factuur-mail',['RVAZ_Wonen_Invoice_Mail','page']);},40);
add_action('admin_post_rvaz_wonen_invoice_mail',function(){if(!current_user_can('manage_options'))wp_die('Niet toegestaan');$id=absint($_POST['id']??0);if(!$id||!wp_verify_nonce($_POST['nonce']??'','rvaz_wonen_invoice_mail_'.$id))wp_die('Ongeldige bevestiging.');$op=sanitize_key($_POST['operation']??'');if($op==='save')$r=RVAZ_Wonen_Invoice_Mail::save_link($id,$_POST['tikkie_url']??'');elseif($op==='send'&&!empty($_POST['confirm']))$r=RVAZ_Wonen_Invoice_Mail::send($id);else wp_die('Bevestig de verzending.');if(is_wp_error($r))wp_die(esc_html($r->get_error_message()));wp_safe_redirect(admin_url('admin.php?page=rvaz-wonen-factuur-mail'));exit;});
