<?php
if(!defined('ABSPATH'))exit;
add_action('wp_enqueue_scripts',function(){if(!class_exists('RVAZ_Wonen')||!is_page(['wonen','mijn-wonen']))return;wp_enqueue_script('rvaz-private',plugins_url('private-website.js',__FILE__),[], '1.2.0',true);wp_add_inline_script('rvaz-private','window.rvazPrivate='.wp_json_encode(['api'=>rest_url(RVAZ_Wonen_Native_API::NS),'nonce'=>is_user_logged_in()?wp_create_nonce('wp_rest'):'','login'=>wp_login_url(get_permalink()),'admin'=>false]).';','before');});
add_filter('do_shortcode_tag',function($output,$tag){if(in_array($tag,['rvaz_wonen','rvaz_wonen_portal'],true))$output.='<section class="rvaz-reader"><h2>Zelf je woning verkopen</h2><p>Particulier aanbod: €25 voor één woning, één kalendermaand vanaf publicatie. Geen automatische verlenging. RVAZ controleert je inzending eerst. De woning verschijnt na goedkeuring en bevestigde betaling.</p><div id="rvaz-private-root" aria-live="polite"></div></section>';return $output;},30,2);
add_action('admin_menu',function(){if(class_exists('RVAZ_Wonen'))add_submenu_page('rvaz-wonen','Particulier aanbod','Particulier aanbod','manage_options','rvaz-wonen-particulier',function(){
 if(!current_user_can('manage_options'))return;echo '<div class="wrap"><h1>Particulier aanbod beoordelen</h1><p>Controleer bevoegdheid, woninggegevens en rechten op de foto’s. De eerste goedkeuring stelt de eigenaar in staat een factuur van €25 aan te vragen. Na betaling: nogmaals goedkeuren om te publiceren. De plaatsingsmaand begint dan pas.</p><p><a href="'.esc_url(admin_url('admin.php?page=rvaz-wonen-facturen')).'">Betaalstatus van facturen beheren</a></p><div id="rvaz-private-root" aria-live="polite"></div></div>';
 wp_enqueue_script('rvaz-private',plugins_url('private-website.js',__FILE__),[], '1.2.0',true);wp_add_inline_script('rvaz-private','window.rvazPrivate='.wp_json_encode(['api'=>rest_url(RVAZ_Wonen_Native_API::NS),'nonce'=>wp_create_nonce('wp_rest'),'admin'=>true,'rows'=>array_map(function($p){$d=RVAZ_Wonen_Native_API::listing($p->ID,true);$d['edit_url']=get_edit_post_link($p->ID,'raw');$d['owner_email']=get_userdata($p->post_author)->user_email;return $d;},get_posts(['post_type'=>RVAZ_Wonen::TYPE,'post_status'=>['draft','pending','publish'],'numberposts'=>-1,'meta_key'=>RVAZ_Wonen_Private::FLAG,'meta_value'=>'1']))]).';','before');
 });},30);
add_filter('the_content',function($content){
 if(!class_exists('RVAZ_Wonen')||!is_singular(RVAZ_Wonen::TYPE)||!in_the_loop()||!is_main_query()||!RVAZ_Wonen_Private::is_private(get_the_ID()))return $content;
 $id=get_the_ID();if(get_post_status($id)!=='publish')return '<p>Deze woning is niet meer beschikbaar.</p>';$d=RVAZ_Wonen_Native_API::listing($id);$b=RVAZ_Wonen::css().'<div class="rvw rvw-public"><div class="rvw-panel"><p class="rvw-badge">Particulier aanbod</p><h1>'.esc_html($d['title']).'</h1><p>'.esc_html($d['postcode'].' '.$d['plaats']).'</p><h2>€ '.esc_html($d['prijs']).'</h2>';
 foreach(array_unique(array_filter(array_merge([$d['image']],$d['gallery']))) as $url)$b.='<img src="'.esc_url($url).'" alt="'.esc_attr($d['title']).'" style="max-width:100%;height:auto">';
 $b.='<h2>Omschrijving</h2>'.wp_kses_post($d['description']).'<h2>Kenmerken</h2><dl>';foreach(['status'=>'Status','woningtype'=>'Soort woning','bouwjaar'=>'Bouwjaar','kamers'=>'Kamers','woonoppervlak'=>'Woonoppervlakte','energielabel'=>'Energielabel','perceel'=>'Perceel','slaapkamers'=>'Slaapkamers','badkamers'=>'Badkamers','tuin'=>'Tuin','garage'=>'Garage','aanvaarding'=>'Aanvaarding'] as $k=>$label)if($d[$k]!=='')$b.='<dt>'.esc_html($label).'</dt><dd>'.esc_html($d[$k]).'</dd>';
 $b.='</dl><h2>Neem contact op met de verkoper</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="rvaz_wonen_contact"><input type="hidden" name="property_id" value="'.$id.'">'.wp_nonce_field('rvaz_wonen_contact_'.$id,'nonce',true,false).'<label>Naam<input name="name" required></label><label>E-mail<input name="email" type="email" required></label><label>Telefoon<input name="phone" type="tel"></label><label>Bericht<textarea name="message" required></textarea></label><button class="rvw-btn">Bericht sturen</button></form></div></div>';return $b;
},30);
// Labels are added server-side to the existing public listing cards.
add_filter('do_shortcode_tag',function($output,$tag){if($tag!=='rvaz_wonen')return $output;foreach(get_posts(['post_type'=>RVAZ_Wonen::TYPE,'post_status'=>'publish','numberposts'=>100,'meta_key'=>RVAZ_Wonen_Private::FLAG,'meta_value'=>'1']) as $p){$needle='<a href="'.esc_url(get_permalink($p->ID)).'">';$output=str_replace($needle,$needle.'<span class="rvw-badge">Particulier aanbod</span>',$output);}return $output;},25,2);
